version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=$GIN_MODE
      - APP_PORT=$APP_PORT
      - MYSQL_HOST=$DB_HOST
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DB=$DB_NAME
      - MYSQL_USER=$DB_USER
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3366:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
