name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22  # ou a versão que você estiver usando

    - name: Install dependencies
      run: go mod tidy

    - name: Run Go Linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.59.1  # ou a versão mais recente do golangci-lint
