name: SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18  # ou a versão que você estiver usando

    - name: Install dependencies
      run: go mod tidy

    - name: Run Go SAST
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...
